/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "sctm.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Transfer, Transfer, AUTO)


PB_BIND(node_info_req_t, node_info_req_t, AUTO)


PB_BIND(node_info_rsp_t, node_info_rsp_t, AUTO)



/* @@protoc_insertion_point(eof) */
